insert into City (id, name, state_id) values (1, 'Simao', 166);
insert into City (id, name, state_id) values (2, 'Philadelphia', 10);
insert into City (id, name, state_id) values (3, 'Petrov', 105);
insert into City (id, name, state_id) values (4, 'Bourg-lès-Valence', 113);
insert into City (id, name, state_id) values (5, 'Jugezhuang', 184);
insert into City (id, name, state_id) values (6, 'Xinyang', 23);
insert into City (id, name, state_id) values (7, 'Al Ain', 20);
insert into City (id, name, state_id) values (8, 'Curumaní', 79);
insert into City (id, name, state_id) values (9, 'Taiping', 118);
insert into City (id, name, state_id) values (10, 'Łazy', 183);
insert into City (id, name, state_id) values (11, 'Tomingad', 130);
insert into City (id, name, state_id) values (12, 'Pangao', 28);
insert into City (id, name, state_id) values (13, 'Boulaouane', 8);
insert into City (id, name, state_id) values (14, 'Węgliniec', 39);
insert into City (id, name, state_id) values (15, 'Longbu', 87);
insert into City (id, name, state_id) values (16, 'Pende', 112);
insert into City (id, name, state_id) values (17, 'Barotac Nuevo', 42);
insert into City (id, name, state_id) values (18, 'Chicoana', 151);
insert into City (id, name, state_id) values (19, 'Mirsíni', 181);
insert into City (id, name, state_id) values (20, 'Mirandopólis', 95);
insert into City (id, name, state_id) values (21, 'Bagadó', 10);
insert into City (id, name, state_id) values (22, 'Mooka', 134);
insert into City (id, name, state_id) values (23, 'Labège', 101);
insert into City (id, name, state_id) values (24, 'Damiao', 191);
insert into City (id, name, state_id) values (25, 'Shangyuan', 191);
insert into City (id, name, state_id) values (26, 'Loyola', 184);
insert into City (id, name, state_id) values (27, 'Babakan', 198);
insert into City (id, name, state_id) values (28, 'San José', 93);
insert into City (id, name, state_id) values (29, 'Yëlkino', 51);
insert into City (id, name, state_id) values (30, 'Riah', 171);
insert into City (id, name, state_id) values (31, 'Phoenix', 185);
insert into City (id, name, state_id) values (32, 'Taichung', 145);
insert into City (id, name, state_id) values (33, 'Žleby', 159);
insert into City (id, name, state_id) values (34, 'Matina', 119);
insert into City (id, name, state_id) values (35, 'Ad Dawḩah', 167);
insert into City (id, name, state_id) values (36, 'Hantsport', 185);
insert into City (id, name, state_id) values (37, 'Springfield', 11);
insert into City (id, name, state_id) values (38, 'Vyshneve', 114);
insert into City (id, name, state_id) values (39, 'Santa Rosa', 3);
insert into City (id, name, state_id) values (40, 'Siayan', 169);
insert into City (id, name, state_id) values (41, 'Jingdu', 117);
insert into City (id, name, state_id) values (42, 'Messina', 79);
insert into City (id, name, state_id) values (43, 'Cilegong', 7);
insert into City (id, name, state_id) values (44, 'Pizarrete', 160);
insert into City (id, name, state_id) values (45, 'Qarshi', 96);
insert into City (id, name, state_id) values (46, 'Postoloprty', 56);
insert into City (id, name, state_id) values (47, 'Biruinţa', 29);
insert into City (id, name, state_id) values (48, 'Toulon', 40);
insert into City (id, name, state_id) values (49, 'Heting', 174);
insert into City (id, name, state_id) values (50, 'Blama', 7);
insert into City (id, name, state_id) values (51, 'Wangzuo', 86);
insert into City (id, name, state_id) values (52, 'Kari', 72);
insert into City (id, name, state_id) values (53, 'Nunsena', 191);
insert into City (id, name, state_id) values (54, 'Librazhd-Qendër', 150);
insert into City (id, name, state_id) values (55, 'Vodňany', 39);
insert into City (id, name, state_id) values (56, 'Cikupa', 34);
insert into City (id, name, state_id) values (57, 'Mafraq', 116);
insert into City (id, name, state_id) values (58, 'Natitingou', 109);
insert into City (id, name, state_id) values (59, 'El Cairo', 76);
insert into City (id, name, state_id) values (60, 'Nara-shi', 21);
insert into City (id, name, state_id) values (61, 'Meia Via', 83);
insert into City (id, name, state_id) values (62, 'Shanglian', 79);
insert into City (id, name, state_id) values (63, 'Prior Velho', 165);
insert into City (id, name, state_id) values (64, 'Ceelbuur', 119);
insert into City (id, name, state_id) values (65, 'Hisings Kärra', 50);
insert into City (id, name, state_id) values (66, 'Mvomero', 34);
insert into City (id, name, state_id) values (67, 'Situbondo', 168);
insert into City (id, name, state_id) values (68, 'Higashine', 117);
insert into City (id, name, state_id) values (69, 'Rueil-Malmaison', 2);
insert into City (id, name, state_id) values (70, 'Brok', 1);
insert into City (id, name, state_id) values (71, 'Victoria', 180);
insert into City (id, name, state_id) values (72, 'Naga', 91);
insert into City (id, name, state_id) values (73, 'Shawnee Mission', 104);
insert into City (id, name, state_id) values (74, 'Ananea', 193);
insert into City (id, name, state_id) values (75, 'Orekhovo-Borisovo Severnoye', 150);
insert into City (id, name, state_id) values (76, 'Erqu', 120);
insert into City (id, name, state_id) values (77, 'Pujilí', 162);
insert into City (id, name, state_id) values (78, 'Åkersberga', 159);
insert into City (id, name, state_id) values (79, 'Badagry', 26);
insert into City (id, name, state_id) values (80, 'Matagalpa', 169);
insert into City (id, name, state_id) values (81, 'Colca', 1);
insert into City (id, name, state_id) values (82, 'Pa Phayom', 123);
insert into City (id, name, state_id) values (83, 'Krasiczyn', 111);
insert into City (id, name, state_id) values (84, 'Cogtong', 5);
insert into City (id, name, state_id) values (85, 'Wucheng', 114);
insert into City (id, name, state_id) values (86, 'Carvalheira', 122);
insert into City (id, name, state_id) values (87, 'Podgornaya', 44);
insert into City (id, name, state_id) values (88, 'Boucherville', 102);
insert into City (id, name, state_id) values (89, 'Cincinnati', 148);
insert into City (id, name, state_id) values (90, 'Mbala', 95);
insert into City (id, name, state_id) values (91, 'Bogorejo', 146);
insert into City (id, name, state_id) values (92, 'Weetombo', 167);
insert into City (id, name, state_id) values (93, 'Cruzeiro', 113);
insert into City (id, name, state_id) values (94, 'Yaogu', 181);
insert into City (id, name, state_id) values (95, 'Monte de Trigo', 128);
insert into City (id, name, state_id) values (96, 'Kano', 148);
insert into City (id, name, state_id) values (97, 'Laḩij', 40);
insert into City (id, name, state_id) values (98, 'Štore', 27);
insert into City (id, name, state_id) values (99, 'Dongqu', 103);
insert into City (id, name, state_id) values (100, 'Stakhanov', 46);
insert into City (id, name, state_id) values (101, 'Sakrand', 127);
insert into City (id, name, state_id) values (102, 'Nyrkiv', 119);
insert into City (id, name, state_id) values (103, 'Frampol', 111);
insert into City (id, name, state_id) values (104, 'Tangguhang', 85);
insert into City (id, name, state_id) values (105, 'Caen', 13);
insert into City (id, name, state_id) values (106, 'Ngadri', 32);
insert into City (id, name, state_id) values (107, 'Boshan', 122);
insert into City (id, name, state_id) values (108, 'Cotuí', 153);
insert into City (id, name, state_id) values (109, 'Marília', 111);
insert into City (id, name, state_id) values (110, 'Talavera', 171);
insert into City (id, name, state_id) values (111, 'Nam Som', 6);
insert into City (id, name, state_id) values (112, 'Frampol', 158);
insert into City (id, name, state_id) values (113, 'Alegrete', 160);
insert into City (id, name, state_id) values (114, 'Songmuping', 198);
insert into City (id, name, state_id) values (115, 'Samagaltay', 79);
insert into City (id, name, state_id) values (116, 'San Rafael', 40);
insert into City (id, name, state_id) values (117, 'Eqbālīyeh', 126);
insert into City (id, name, state_id) values (118, 'Hezuoqiao', 117);
insert into City (id, name, state_id) values (119, 'Pasrūr', 27);
insert into City (id, name, state_id) values (120, 'Fuente de Oro', 170);
insert into City (id, name, state_id) values (121, 'Saraza', 138);
insert into City (id, name, state_id) values (122, 'Kangani', 128);
insert into City (id, name, state_id) values (123, 'Santo Anastácio', 118);
insert into City (id, name, state_id) values (124, 'Sihai', 114);
insert into City (id, name, state_id) values (125, 'Baganhilir', 42);
insert into City (id, name, state_id) values (126, 'Stockholm', 16);
insert into City (id, name, state_id) values (127, 'Budapest', 149);
insert into City (id, name, state_id) values (128, 'Martakert', 70);
insert into City (id, name, state_id) values (129, 'Evinayong', 88);
insert into City (id, name, state_id) values (130, 'Szelków', 53);
insert into City (id, name, state_id) values (131, 'Saint Petersburg', 119);
insert into City (id, name, state_id) values (132, 'Nizami', 194);
insert into City (id, name, state_id) values (133, 'Wólka Pełkińska', 144);
insert into City (id, name, state_id) values (134, 'Ríohacha', 182);
insert into City (id, name, state_id) values (135, 'Airdrie', 95);
insert into City (id, name, state_id) values (136, 'Polyarnyy', 10);
insert into City (id, name, state_id) values (137, 'Placer', 13);
insert into City (id, name, state_id) values (138, 'Santa Lucia', 47);
insert into City (id, name, state_id) values (139, 'Rizal', 189);
insert into City (id, name, state_id) values (140, 'Baolong', 158);
insert into City (id, name, state_id) values (141, 'Omigawa', 177);
insert into City (id, name, state_id) values (142, 'Cilegong', 34);
insert into City (id, name, state_id) values (143, 'Salinas', 199);
insert into City (id, name, state_id) values (144, 'Mityana', 105);
insert into City (id, name, state_id) values (145, 'Puńsk', 49);
insert into City (id, name, state_id) values (146, 'Chimbote', 46);
insert into City (id, name, state_id) values (147, 'Qozonketkan', 127);
insert into City (id, name, state_id) values (148, 'Jinchang', 169);
insert into City (id, name, state_id) values (149, 'Nova Friburgo', 163);
insert into City (id, name, state_id) values (150, 'Bejuco', 99);
insert into City (id, name, state_id) values (151, 'Wuyo', 47);
insert into City (id, name, state_id) values (152, 'Kokterek', 144);
insert into City (id, name, state_id) values (153, 'Panalanoy', 44);
insert into City (id, name, state_id) values (154, 'Sandviken', 76);
insert into City (id, name, state_id) values (155, 'Aoufous', 197);
insert into City (id, name, state_id) values (156, 'Prainha de Baixo', 145);
insert into City (id, name, state_id) values (157, 'Cruzeiro do Sul', 59);
insert into City (id, name, state_id) values (158, 'Booterstown', 85);
insert into City (id, name, state_id) values (159, 'Lleida', 66);
insert into City (id, name, state_id) values (160, 'Durham', 35);
insert into City (id, name, state_id) values (161, 'El Tambo', 138);
insert into City (id, name, state_id) values (162, 'Luzhou', 72);
insert into City (id, name, state_id) values (163, 'Kuala Terengganu', 107);
insert into City (id, name, state_id) values (164, 'Xunqiao', 17);
insert into City (id, name, state_id) values (165, 'Martakert', 68);
insert into City (id, name, state_id) values (166, 'Lafiagi', 21);
insert into City (id, name, state_id) values (167, 'Digne-les-Bains', 17);
insert into City (id, name, state_id) values (168, 'Babice', 104);
insert into City (id, name, state_id) values (169, 'Buinsk', 146);
insert into City (id, name, state_id) values (170, 'Santa Cruz', 45);
insert into City (id, name, state_id) values (171, 'Oibioin', 187);
insert into City (id, name, state_id) values (172, 'Arboleda', 40);
insert into City (id, name, state_id) values (173, 'Novo-Peredelkino', 52);
insert into City (id, name, state_id) values (174, 'Enonkoski', 200);
insert into City (id, name, state_id) values (175, 'Changtang', 170);
insert into City (id, name, state_id) values (176, 'San Francisco', 71);
insert into City (id, name, state_id) values (177, 'Būrkah', 98);
insert into City (id, name, state_id) values (178, 'Zhangfeng', 159);
insert into City (id, name, state_id) values (179, 'Heyan', 179);
insert into City (id, name, state_id) values (180, 'Chenguang', 111);
insert into City (id, name, state_id) values (181, 'La Rochelle', 174);
insert into City (id, name, state_id) values (182, 'Pākpattan', 96);
insert into City (id, name, state_id) values (183, 'Puan', 138);
insert into City (id, name, state_id) values (184, 'Nueva Germania', 34);
insert into City (id, name, state_id) values (185, 'Staryy Saltiv', 54);
insert into City (id, name, state_id) values (186, 'Nyimba', 143);
insert into City (id, name, state_id) values (187, 'Rila', 127);
insert into City (id, name, state_id) values (188, 'Cesson', 94);
insert into City (id, name, state_id) values (189, 'Huddinge', 12);
insert into City (id, name, state_id) values (190, 'Tam Bình', 67);
insert into City (id, name, state_id) values (191, 'Koroška Bela', 47);
insert into City (id, name, state_id) values (192, 'Mweka', 99);
insert into City (id, name, state_id) values (193, 'Concepcion', 172);
insert into City (id, name, state_id) values (194, 'Hai Riêng', 118);
insert into City (id, name, state_id) values (195, 'Dawang', 189);
insert into City (id, name, state_id) values (196, 'Muzayri‘', 178);
insert into City (id, name, state_id) values (197, 'Bueng Samakkhi', 93);
insert into City (id, name, state_id) values (198, 'Evansville', 9);
insert into City (id, name, state_id) values (199, 'Perovo', 134);
insert into City (id, name, state_id) values (200, 'Corpus Christi', 183);
insert into City (id, name, state_id) values (201, 'Semenivka', 165);
insert into City (id, name, state_id) values (202, 'Keleleng', 164);
insert into City (id, name, state_id) values (203, 'Santa Fe', 167);
insert into City (id, name, state_id) values (204, 'Saint-Égrève', 8);
insert into City (id, name, state_id) values (205, 'Zoumaping', 46);
insert into City (id, name, state_id) values (206, 'Curpahuasi', 170);
insert into City (id, name, state_id) values (207, 'Rumelange', 105);
insert into City (id, name, state_id) values (208, 'Plaeng Yao', 175);
insert into City (id, name, state_id) values (209, 'Meylan', 74);
insert into City (id, name, state_id) values (210, 'Balayang', 77);
insert into City (id, name, state_id) values (211, 'Dologon', 120);
insert into City (id, name, state_id) values (212, 'Yuxi', 103);
insert into City (id, name, state_id) values (213, 'Palmas', 115);
insert into City (id, name, state_id) values (214, 'Soljani', 113);
insert into City (id, name, state_id) values (215, 'Pianbai', 42);
insert into City (id, name, state_id) values (216, 'Molinos', 121);
insert into City (id, name, state_id) values (217, 'Daleman', 84);
insert into City (id, name, state_id) values (218, 'Kompóti', 88);
insert into City (id, name, state_id) values (219, 'Santo Domingo Oeste', 141);
insert into City (id, name, state_id) values (220, 'Dolod', 8);
insert into City (id, name, state_id) values (221, 'Kota Ternate', 11);
insert into City (id, name, state_id) values (222, 'Göteborg', 176);
insert into City (id, name, state_id) values (223, 'Hollola', 85);
insert into City (id, name, state_id) values (224, 'Norrköping', 63);
insert into City (id, name, state_id) values (225, 'Íquira', 104);
insert into City (id, name, state_id) values (226, 'Santa Cruz de la Sierra', 127);
insert into City (id, name, state_id) values (227, 'Troyes', 33);
insert into City (id, name, state_id) values (228, 'Dovhe', 93);
insert into City (id, name, state_id) values (229, 'Ipoh', 176);
insert into City (id, name, state_id) values (230, 'Mengxingzhuang', 99);
insert into City (id, name, state_id) values (231, 'Imari', 14);
insert into City (id, name, state_id) values (232, 'Longueuil', 29);
insert into City (id, name, state_id) values (233, 'Jinan', 165);
insert into City (id, name, state_id) values (234, 'Samara', 89);
insert into City (id, name, state_id) values (235, 'Shetangpo', 52);
insert into City (id, name, state_id) values (236, 'Plaški', 183);
insert into City (id, name, state_id) values (237, 'El Quiteño', 102);
insert into City (id, name, state_id) values (238, 'Wangying', 189);
insert into City (id, name, state_id) values (239, 'Jiangduo', 100);
insert into City (id, name, state_id) values (240, 'Svoge', 31);
insert into City (id, name, state_id) values (241, 'Jammāl', 50);
insert into City (id, name, state_id) values (242, 'Shatki', 47);
insert into City (id, name, state_id) values (243, 'Qingfeng', 191);
insert into City (id, name, state_id) values (244, 'Farīmān', 65);
insert into City (id, name, state_id) values (245, 'Ewirgol', 44);
insert into City (id, name, state_id) values (246, 'Esperantina', 45);
insert into City (id, name, state_id) values (247, 'Baddomalhi', 182);
insert into City (id, name, state_id) values (248, 'Slovenski Javornik', 82);
insert into City (id, name, state_id) values (249, 'Santiago', 152);
insert into City (id, name, state_id) values (250, 'Tupanciretã', 26);
insert into City (id, name, state_id) values (251, 'Xiaozhai', 198);
insert into City (id, name, state_id) values (252, 'Motomiya', 96);
insert into City (id, name, state_id) values (253, 'Krynychky', 177);
insert into City (id, name, state_id) values (254, 'Andkhōy', 54);
insert into City (id, name, state_id) values (255, 'Sundbyberg', 120);
insert into City (id, name, state_id) values (256, 'Dongbei', 76);
insert into City (id, name, state_id) values (257, 'Talospatang', 159);
insert into City (id, name, state_id) values (258, 'Huyuan', 184);
insert into City (id, name, state_id) values (259, 'Uspenskoye', 43);
insert into City (id, name, state_id) values (260, 'Athy', 145);
insert into City (id, name, state_id) values (261, 'Piraí do Sul', 172);
insert into City (id, name, state_id) values (262, 'Nanterre', 138);
insert into City (id, name, state_id) values (263, 'Woken', 32);
insert into City (id, name, state_id) values (264, 'Jiangchuan', 114);
insert into City (id, name, state_id) values (265, 'Na Klang', 15);
insert into City (id, name, state_id) values (266, 'Bekondo', 13);
insert into City (id, name, state_id) values (267, 'Tsotsin-Yurt', 61);
insert into City (id, name, state_id) values (268, 'Ocala', 96);
insert into City (id, name, state_id) values (269, 'Seaforth', 85);
insert into City (id, name, state_id) values (270, 'Sidomulyo', 88);
insert into City (id, name, state_id) values (271, 'Ojrzeń', 157);
insert into City (id, name, state_id) values (272, 'Sokolnice', 190);
insert into City (id, name, state_id) values (273, 'Bachok', 155);
insert into City (id, name, state_id) values (274, 'Maluko', 50);
insert into City (id, name, state_id) values (275, 'Jishi', 48);
insert into City (id, name, state_id) values (276, 'Mabua', 181);
insert into City (id, name, state_id) values (277, 'Dambarta', 113);
insert into City (id, name, state_id) values (278, 'Wasogolo', 154);
insert into City (id, name, state_id) values (279, 'Dasha', 176);
insert into City (id, name, state_id) values (280, 'Barinitas', 81);
insert into City (id, name, state_id) values (281, 'Sedayulawas', 71);
insert into City (id, name, state_id) values (282, 'Alcainça', 47);
insert into City (id, name, state_id) values (283, 'Orocué', 167);
insert into City (id, name, state_id) values (284, 'Santa Fé do Sul', 188);
insert into City (id, name, state_id) values (285, 'Rappang', 75);
insert into City (id, name, state_id) values (286, 'Alicante/Alacant', 173);
insert into City (id, name, state_id) values (287, 'Chengxi', 163);
insert into City (id, name, state_id) values (288, 'Paucar', 3);
insert into City (id, name, state_id) values (289, 'Huangjin', 140);
insert into City (id, name, state_id) values (290, 'Kramsk', 25);
insert into City (id, name, state_id) values (291, 'Balakhta', 63);
insert into City (id, name, state_id) values (292, 'Gällivare', 168);
insert into City (id, name, state_id) values (293, 'Horodyshche', 181);
insert into City (id, name, state_id) values (294, 'Padina', 193);
insert into City (id, name, state_id) values (295, 'São Martinho', 41);
insert into City (id, name, state_id) values (296, 'Bulacan', 32);
insert into City (id, name, state_id) values (297, 'Saint-Denis', 32);
insert into City (id, name, state_id) values (298, 'Lujing Zhen', 68);
insert into City (id, name, state_id) values (299, 'Motala', 63);
insert into City (id, name, state_id) values (300, 'Krajan Suco', 163);
INSERT INTO City (id, name, state_id)
VALUES (301, 'Split', 1)
ON CONFLICT (id) DO NOTHING;